"""add none

Revision ID: 3bab22f3105b
Revises: 7af0da5bbd06
Create Date: 2024-11-14 18:07:41.085268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bab22f3105b'
down_revision: Union[str, None] = '7af0da5bbd06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tg_interactions', 'reply_on_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('tg_interactions_message_chat_id_message_id_fkey', 'tg_interactions', type_='foreignkey')
    op.drop_constraint('tg_interactions_reply_on_chat_id_reply_on_id_fkey', 'tg_interactions', type_='foreignkey')
    op.create_foreign_key(None, 'tg_interactions', 'tg_messages', ['chat_id', 'message_id'], ['chat_id', 'id'])
    op.create_foreign_key(None, 'tg_interactions', 'tg_messages', ['chat_id', 'reply_on_id'], ['chat_id', 'id'])
    op.drop_column('tg_interactions', 'message_chat_id')
    op.drop_column('tg_interactions', 'reply_on_chat_id')
    op.alter_column('tg_messages', 'statistics',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tg_messages', 'statistics',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('tg_interactions', sa.Column('reply_on_chat_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tg_interactions', sa.Column('message_chat_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tg_interactions', type_='foreignkey')
    op.drop_constraint(None, 'tg_interactions', type_='foreignkey')
    op.create_foreign_key('tg_interactions_reply_on_chat_id_reply_on_id_fkey', 'tg_interactions', 'tg_messages', ['reply_on_chat_id', 'reply_on_id'], ['chat_id', 'id'])
    op.create_foreign_key('tg_interactions_message_chat_id_message_id_fkey', 'tg_interactions', 'tg_messages', ['message_chat_id', 'message_id'], ['chat_id', 'id'])
    op.alter_column('tg_interactions', 'reply_on_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
