"""Update schema

Revision ID: 448821846ebd
Revises: 9ec3c685f898
Create Date: 2024-11-02 12:57:14.365603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '448821846ebd'
down_revision: Union[str, None] = '9ec3c685f898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'chat_id')
    op.add_column('tg_interactions', sa.Column('chat_name', sa.String(), nullable=False))
    op.alter_column('tg_interactions', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('tg_interactions', 'action_from',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('tg_interactions', 'action_to',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.drop_constraint('tg_interactions_chat_id_fkey', 'tg_interactions', type_='foreignkey')
    op.create_foreign_key(None, 'tg_interactions', 'chats', ['chat_name'], ['chat_name'])
    op.drop_column('tg_interactions', 'chat_id')
    op.alter_column('tg_users', 'tg_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('tg_users_tg_id_seq'::regclass)"))
    op.alter_column('users', 'tg_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tg_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('tg_users', 'tg_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('tg_users_tg_id_seq'::regclass)"))
    op.add_column('tg_interactions', sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tg_interactions', type_='foreignkey')
    op.create_foreign_key('tg_interactions_chat_id_fkey', 'tg_interactions', 'chats', ['chat_id'], ['chat_id'])
    op.alter_column('tg_interactions', 'action_to',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('tg_interactions', 'action_from',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('tg_interactions', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('tg_interactions', 'chat_name')
    op.add_column('chats', sa.Column('chat_id', sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
