"""Initial

Revision ID: 8316be428a8b
Revises: 
Create Date: 2024-11-05 18:32:23.945776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8316be428a8b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_chats',
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('chat_name', sa.String(), nullable=False),
    sa.Column('users_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('tg_statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reaction', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tg_users',
    sa.Column('tg_id', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tg_id')
    )
    op.create_table('vk_users',
    sa.Column('vk_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('female', 'male', name='genderenum'), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('education', sa.String(), nullable=True),
    sa.Column('family_status', sa.Enum('not_selected', 'single_female', 'single_male', 'has_boyfriend', 'has_girlfriend', 'engaged_female', 'engaged_male', 'married_female', 'married_male', 'in_love_female', 'in_love_male', 'active_search', 'civil_marriage', name='familystatusenum'), nullable=False),
    sa.Column('friends', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('groups', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('vk_id')
    )
    op.create_table('tg_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('statistics', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['statistics'], ['tg_statistics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vk_id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tg_id'], ['tg_users.tg_id'], ),
    sa.ForeignKeyConstraint(['vk_id'], ['vk_users.vk_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tg_interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('tag', 'react', 'message', 'add_user', 'reply', 'delete', 'forward', name='tgactionenum'), nullable=False),
    sa.Column('action_from', sa.String(), nullable=False),
    sa.Column('action_to', sa.String(), nullable=True),
    sa.Column('reply_on', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_from'], ['tg_users.tg_id'], ),
    sa.ForeignKeyConstraint(['action_to'], ['tg_users.tg_id'], ),
    sa.ForeignKeyConstraint(['chat_id'], ['tg_chats.chat_id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['tg_messages.id'], ),
    sa.ForeignKeyConstraint(['reply_on'], ['tg_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vk_posts',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('music', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('posted_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['posted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('vk_interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('like', 'comment', 'post', name='vkactionenum'), nullable=False),
    sa.Column('action_from', sa.Integer(), nullable=False),
    sa.Column('action_to', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_from'], ['vk_users.vk_id'], ),
    sa.ForeignKeyConstraint(['action_to'], ['vk_users.vk_id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['vk_posts.post_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vk_interactions')
    op.drop_table('vk_posts')
    op.drop_table('tg_interactions')
    op.drop_table('users')
    op.drop_table('tg_messages')
    op.drop_table('vk_users')
    op.drop_table('tg_users')
    op.drop_table('tg_statistics')
    op.drop_table('tg_chats')
    # ### end Alembic commands ###
    op.execute('DROP TYPE IF EXISTS genderenum')
    op.execute('DROP TYPE IF EXISTS familystatusenum')
    op.execute('DROP TYPE IF EXISTS tgactionenum')
    op.execute('DROP TYPE IF EXISTS vkactionenum')